services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "3000:80"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
