name: Despliegue Automático Proxmox

# ¿Cuándo se ejecuta esto? Cuando alguien haga un "push" a la rama "main"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # ¿Dónde se ejecuta esto? En tu servidor (el agente que acabas de instalar)
    runs-on: self-hosted

    steps:
      - name: 📥 Descargar nuevo código desde GitHub
        uses: actions/checkout@v4

      - name: ⚙️ Preparar entorno
        run: |
          # Inyectamos los secretos de GitHub en el archivo .env del servidor
          echo "WORDPRESS_API_URL=${{ secrets.WORDPRESS_API_URL }}" > .env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env

          # Aseguramos que la red de proxy exista. Si no existe, la crea. Si ya existe, ignora el error (|| true)
          docker network create proxy-network || true

      - name: 🚀 Compilar y Desplegar con Docker
        run: |
          # El agente ejecuta el comando de despliegue automáticamente
          docker compose up -d --build --force-recreate

      - name: 🧹 Limpieza de Servidor
        run: |
          # Borramos las imágenes viejas de Docker para no llenar el disco de Proxmox
          docker system prune -f
